server:
  port: 8090

spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/dbdemo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
message:
  config: Hellooo
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/dbdemo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
message:
  config: Hellooo

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/dbdemo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
message:
  config: Hellooo